### PR TITLE
add colorized Icons

### PR DESCRIPTION
**Pull request by DrMabuse23**
Hi it would be nice to have some colors on the icons i hope its the right place

### CODE REVIEW

**Comment by brandyscarney** [comment]
I tested this using `<icon information-circle item-right dark></icon>` but changed `dark` to all of the  different colors. Seems `dark` and `danger` try to add those attributes as icons. cc @adamdbradley

**Comment by adamdbradley** [comment]
Sorry but there's been some restructuring to the icons directive. But I'll add in the ability to add icon colors, thanks.

**Comment by adamdbradley** [comment]
https://github.com/driftyco/ionic2/commit/e5aeff828dd540cdf747629613ab27744e321c42

**Comment by DrMabuse23** [comment]
:+1:

**Pull request closed without merging**
