### PR TITLE
chips component

### PR DESCRIPTION
**Pull request by 3dd13**
implement chips component for issue https://github.com/driftyco/ionic2/issues/846

##### Usage

    <p>
      <ion-chip>
        <ion-label>Default</ion-label>
      </ion-chip>
    </p>

##### Visual
screen shot 2016-01-07 at 18 08 24

##### Usage
    <p>
      <ion-chip>
        <ion-icon name="pin"></ion-icon>
        <ion-label>Default</ion-label>
      </ion-chip>
    </p>
    <p>
      <ion-chip>
        <ion-icon name="pin" primary></ion-icon>
        <ion-label>Primary</ion-label>
      </ion-chip>
    </p>
##### Visual
screen shot 2016-01-07 at 18 08 35

##### Usage
    <p>
      <ion-chip>
        <ion-avatar>
          
        </ion-avatar>
        <ion-label>Default</ion-label>
      </ion-chip>
    </p>

##### Visual
screen shot 2016-01-07 at 18 08 43

##### Usage
    <p>
      <ion-chip>
        <ion-label>Default</ion-label>
        <button clear dark (click)="deleteClicked()">
          <ion-icon name="close-circle"></ion-icon>
        </button>
      </ion-chip>
    </p>

    <p>
      <ion-chip>
        <ion-icon name="pin" primary></ion-icon>
        <ion-label>Primary</ion-label>
        <button clear dark (click)="deleteClicked()">
          <ion-icon name="close-circle"></ion-icon>
        </button>
      </ion-chip>
    </p>

    <p>
      <ion-chip>
        <ion-avatar>
          
        </ion-avatar>
        <ion-label>Default</ion-label>
        <button clear dark (click)="deleteClicked()">
          <ion-icon name="close-circle"></ion-icon>
        </button>
      </ion-chip>
    </p>

##### Visual
screen shot 2016-01-07 at 18 08 49

### CODE REVIEW

**Comment by 3dd13** [comment]
this is my try on chip component

for the delete button on right, not sure if it is good to insert to dom as directive or not.
it may be too magic and less customizable:

    <ion-chip delete (deleteClick)="doDelete()">
      <ion-label>Default</ion-label>
    </ion-chip>

**Comment by swarthout** [comment]
First of all, thank you for implementing this component! When I was thinking of this component's design earlier this week, I ran into this same question of the "magic delete". While I love the beauty of the custom event emitter and personally would be happy with it, I know the ionic team is stressing the importance of customizability in this release. Perhaps it would be possible to extract some properties of the delete button (color, icon, etc.) into sass variables for customization that way?

**Comment by adamdbradley** [comment]
This is great, thanks! I think we'll keep it undocumented for a little while as we go over the css and make sure it's fitting in with the framework. Thanks for the PR and awesome work!

**Comment by DavidVeloso** [comment]
This is great!!!
It's possible use ion-chip on <form> like md-chips (angular material) ? Ex: https://material.angularjs.org/latest/demo/chips

Thanks! (':

**Pull request merged**
